### ISSUE TITLE
bandwidth.html not displaying graphs

### ISSUE THREAD

**Issue by tjirku** [gonzalo/html-bandwidth-report#1]
Hey Gonzalo - i was super excited about your bandwidth project on Git - 
downloaded it, installed it according to your description on a freshly installed apache on my raspberry,
but when i call the "http://URLofmyRASPI:80/bandwidth.html" it displays the html page in git style :) 
any idea what i am missing ??

**Comment by gonzalo** [comment]
I'm not sure what do you mean with "git style", 
Are you sure that you have correctly downloaded the file? You should download the zip file https://github.com/gonzalo/html-bandwidth-report/archive/master.zip and extract the files from there.

**Comment by tjirku** [comment]
gonzalo - thanks - for whatever reason i seemed to have downloaded the wrong file - works now !! love this dashboard !! just imported my speedtest-cli stats and got my ISP reduce my monthly fee and upgrade my download rate :) !!

**Comment by gonzalo** [comment]
Happy to know that this project has been helpfull for someone.

Thanks a lot for your feedback!

**Comment by tjirku** [comment]
Hi Gonzalo - 
just one more thing - you write in your speedtest cli page that you use a modified version of speedtest cli, that is able to do the --csv export for the bandwith.csv file - i am not able to download the version that is able to do the csv export !? am i missing something again ?!? any hint ? appreciate it !!

**Comment by gonzalo** [comment]
Sorry @tjirku I haven't seen your message until today.

Thats right I've realized that is not easy to find the correct modified version of speedtest cli. Here you have https://github.com/gonzalo/speedtest-cli/tree/devel

**Comment by tjirku** [comment]
Hey Gonzalo - 

i was digging a bit 2 days ago and found it - it is working now with the
--csv !! 

love it !! 

Thank you very much for your efforts !!!!! 

Am 29-01-2016 13:16, schrieb Gonzalo Cao Cabeza de Vaca: 

> Sorry @tjirku [1] I haven't seen your message until today. 
> 
> Thats right I've realized that is not easy to find the correct modified version of speedtest cli. Here you have https://github.com/gonzalo/speedtest-cli/tree/devel [2] 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [3].

## Links:

[1] https://github.com/tjirku
[2] https://github.com/gonzalo/speedtest-cli/tree/devel
[3]
https://github.com/gonzalo/html-bandwidth-report/issues/1#issuecomment-176726056
